openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact web app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: keep your contacts save with this web app
tags:
  - name: Contacts
    description: Operations about contacts
servers:
  - url: http://localhost:4000
  - url: https://swagger.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
